steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/datasyncher-kubernetes/datasyncher-frontend:${SHORT_SHA}", "."]
images:
  - "gcr.io/datasyncher-kubernetes/datasyncher-frontend:${SHORT_SHA}"
